### ISSUE TITLE
DICOM SNOMED to ontology mappings master ticket

### ISSUE THREAD

**Issue by gaurav** [cancerDHC/tools#26]
This master ticket tracks everything we want to work on for the DICOM SNOMED to ontology mappings, and establishes a rough chronology in which we want to do all of these things:

Urgent, important:
- [ ] Re-run SNOMED DICOM mappings with new UMLS release (https://github.com/cancerDHC/tools/issues/22)
- [ ] Integrate BioPortal into SNOMED-in-DICOM mappings (https://github.com/cancerDHC/tools/issues/21)
- [ ] Test grouping terms in mapping tool via NCImt hierarchy (https://github.com/cancerDHC/tools/issues/20)
- [ ] Develop methods for validating the DICOM SNOMED mappings (https://github.com/cancerDHC/tools/issues/24)

Urgent, not important:
- [ ] Incorporate additional ontologies into DICOM SNOMED to NCIt mapping (https://github.com/cancerDHC/tools/issues/19)

Not urgent, important:
- [ ] Investigate an instance where we didn't match a SNOMED term correctly through UMLS (https://github.com/cancerDHC/tools/issues/25)
- [ ] Check DICOM SNOMED mappings against mappings already in the DICOM standard (https://github.com/cancerDHC/tools/issues/23)
- [ ] Choose a format for publishing mappings (https://github.com/cancerDHC/tools/issues/3)

Not urgent, not important:
- None.

**Comment by monicacecilia** [comment]
Closing. Please see [/cancerDHC/operations issue #48](https://github.com/cancerDHC/operations/issues/48) for additional information.
h/t @gaurav
